
#ifndef __antnet_common_h__
#define __antnet_common_h__

#include <agent.h>
#include <node.h>
#include <packet.h>
#include <ip.h>
#include <trace.h>
#include <timer-handler.h>
#include <random.h>
#include <classifier-port.h>
#include <tools/rng.h>

#include "trace/cmu-trace.h"
#include "tools/queue-monitor.h"
#include "queue/drop-tail.h"

/// Macro to retrieve current simulator time 
#define CURRENT_TIME Scheduler::instance().clock()

/// Maximum number of nodes in topology
#define MAX_NUM_NODES 16

/// file name in which routing tables generated by AntNet are dumped
#define file_rtable "rtable.txt"

#define DEBUG 0

/// maximum length of observation window
#define WIN_LEN 300
/// AntNet parameters
#define VARSIGMA 0.005
#define ALPHA 0.45	//relative weight of heuristic info w.r.t pheromone
#define c1 0.7
#define c2 0.3
#define zee 1.7

/// Method to return number of neighbors of a node
int get_num_neighbors(nsaddr_t node_addr);

/// Method to return queue length of a link between two nodes
int get_queue_length(Node *node1, Node *node2);
 
#endif
